export default [
  {
    question: 'Name a popular female movie-inspired costume.',
    answers: [
      {points: 20, answer: 'Wonder Woman'},
      {points: 15, answer: 'Cat Woman'},
      {points: 12, answer: 'Cinderella'},
      {points: 10, answer: 'Marilyn Monroe'},
      {points: 7, answer: 'Dorothy (Wizard of Oz)'},
      {points: 5, answer: 'Alice (in Wonderland)'},
      {points: 4, answer: "Scarlett O'Hara (Gone With the Wind)"},
      {points: 4, answer: 'Morticia Adams (Addams Family)'},
      {points: 3, answer: 'Superwoman'},
      {points: 3, answer: 'Hannah Montana'},
      {points: 3, answer: 'Wicked Witch of the West'},
      {points: 3, answer: 'Tinkerbell'},
      {points: 3, answer: 'Princess Leia (Star Wars)'},
      {points: 3, answer: 'Bride of Frankenstein'},
      {points: 2, answer: 'Cleopatra'},
      {points: 2, answer: 'Bat Girl'},
      {points: 2, answer: 'Tabitha (Bewitched)'},
    ],
  },
  {
    question: 'Name a male superhero costume.',
    answers: [
      {points: 68, answer: 'Superman'},
      {points: 18, answer: 'Spiderman'},
      {points: 14, answer: 'Batman'},
    ],
  },
  {
    question: 'Name a halloween prank.',
    answers: [
      {points: 51, answer: 'Toilet papering houses/trees/yar'},
      {points: 20, answer: 'Eggin'},
      {points: 10, answer: 'Soaping window'},
      {points: 7, answer: 'Smashing pumpkin'},
      {points: 7, answer: 'Jumping out and scaring people'},
      {points: 5, answer: 'Ringing doorbells and running away'},
    ],
  },
  {
    question: 'Name a popular halloween treat.',
    answers: [
      {points: 23, answer: 'Snickers Bar'},
      {points: 23, answer: 'Candy'},
      {points: 17, answer: 'Candy Corn'},
      {points: 16, answer: 'Caramel/Candy Apples'},
      {points: 10, answer: 'Popcorn Balls'},
      {points: 9, answer: 'Mini Chocolate Bars'},
      {points: 2, answer: 'Reeses Peanut Butter Cups'},
    ],
  },
  {
    question: 'Name something trick-or-treaters collect candy in.',
    answers: [
      {points: 46, answer: 'Plastic Pumpkin'},
      {points: 28, answer: 'Pillowcase'},
      {points: 24, answer: 'Bag'},
      {points: 2, answer: 'Bucket'},
    ],
  },
  {
    question: 'Name a popular Halloween party decoration.',
    answers: [
      {points: 36, answer: 'Pumpkin/Jack-O-Lantern'},
      {points: 20, answer: 'Spiderwebs/Cobwebs'},
      {points: 14, answer: 'Spiders'},
      {points: 11, answer: 'Ghosts'},
      {points: 10, answer: 'Skeletons'},
      {points: 4, answer: 'Candle'},
      {points: 3, answer: 'Witches'},
      {points: 2, answer: 'Skull'},
    ],
  },
  {
    question: 'Name a game you might play at a Halloween party.',
    answers: [
      {points: 82, answer: 'Bobbing for Apples'},
      {points: 7, answer: 'Hide and Seek'},
      {points: 7, answer: 'Scavenger Hunt'},
      {points: 3, answer: 'Costume Contest'},
    ],
  },
  {
    question: 'Name a superstition associated with Halloween.',
    answers: [
      {points: 77, answer: 'Black Cat (crosses your path, brings bad luck)'},
      {points: 20, answer: 'Ghosts appear/Walking dead'},
      {points: 3, answer: "Don't walk under a ladder"},
    ],
  },
  {
    question: 'Name a scary Halloween character.',
    answers: [
      {points: 20, answer: 'Freddie Krueger'},
      {points: 19, answer: 'Frankenstein'},
      {points: 14, answer: 'Jason (Friday the 13th)'},
      {points: 9, answer: 'Vampire'},
      {points: 8, answer: 'Dracula'},
      {points: 7, answer: 'Grim Reaper'},
      {points: 6, answer: 'Witch'},
      {points: 6, answer: 'Ghost'},
      {points: 4, answer: 'Headless Horseman'},
      {points: 3, answer: 'Mummy'},
      {points: 2, answer: 'Skeleton'},
      {points: 2, answer: 'Zombie'},
    ],
  },
  {
    question: 'Name a popular Halloween movie.',
    answers: [
      {points: 50, answer: 'Halloween'},
      {points: 21, answer: 'Friday the 13th'},
      {points: 8, answer: 'Nightmare on Elm Street'},
      {points: 7, answer: "It's the Great Pumpkin, Charlie Brown"},
      {points: 5, answer: 'Scream'},
      {points: 5, answer: 'Hocus Pocus'},
      {points: 4, answer: 'Frankenstein'},
    ],
  },
  {
    question: 'Name a song popular at Halloween dances.',
    answers: [
      {points: 79, answer: 'Monster Mash'},
      {points: 13, answer: 'Thriller'},
      {points: 4, answer: 'Addams Family Theme'},
      {points: 4, answer: 'Ghostbusters'},
    ],
  },
  {
    question: "Name an accessory essential to a witch's costume.",
    answers: [
      {points: 50, answer: 'Broom'},
      {points: 48, answer: 'Black Hat'},
      {points: 2, answer: 'Pointed Nose'},
    ],
  },
  {
    question: 'Name something that makes a haunted house scary.',
    answers: [
      {points: 40, answer: 'Scary music/noises'},
      {points: 17, answer: 'Darkness'},
      {points: 15, answer: 'Cobwebs/Spiderwebs'},
      {points: 10, answer: 'Ghosts'},
      {points: 6, answer: 'People/Things jumping out at you'},
      {points: 4, answer: 'Strobe Lighting'},
      {points: 4, answer: 'Fog'},
      {points: 2, answer: 'Skulls/Skeletons'},
      {points: 2, answer: 'Bats'},
    ],
  },
  {
    question: 'Name something people decorate their yards with at Halloween.',
    answers: [
      {points: 38, answer: 'Gravestones/Tombstones'},
      {points: 31, answer: 'Pumpkins'},
      {points: 12, answer: 'Cobwebs/Spiderwebs'},
      {points: 5, answer: 'Hay/Straw Bales'},
      {points: 4, answer: 'Ghosts'},
      {points: 4, answer: 'Lights'},
      {points: 3, answer: 'Skeletons'},
      {points: 3, answer: 'Scarecrows'},
    ],
  },
  {
    question: 'Name someone who played a vampire on the big screen.',
    answers: [
      {points: 28, answer: 'Bela Lugosi'},
      {points: 21, answer: 'Robert Pattinson'},
      {points: 15, answer: 'Tom Cruise'},
      {points: 12, answer: 'Boris Karloff'},
      {points: 7, answer: 'Vincent Price'},
      {points: 7, answer: 'Brad Pitt'},
      {points: 5, answer: 'Lon Chaney'},
      {points: 3, answer: 'Christopher Lee'},
      {points: 2, answer: 'George Hamilton'},
    ],
  },
  {
    question: 'Name a popular Halloween cookie cutter shape.',
    answers: [
      {points: 60, answer: 'Pumpkin'},
      {points: 22, answer: 'Ghost'},
      {points: 13, answer: 'Bat'},
      {points: 5, answer: 'Cat'},
    ],
  },
  {
    question: 'What other name is Halloween sometimes known as?',
    answers: [
      {points: 70, answer: 'All Hallows Eve'},
      {points: 13, answer: 'All Saints Day/Eve'},
      {points: 7, answer: 'Trick or Treat Night'},
      {points: 5, answer: "Devil's Night"},
      {points: 5, answer: 'Witches Night'},
    ],
  },
  {
    question: 'Name a scary Halloween sound effect.',
    answers: [
      {points: 38, answer: 'Screams'},
      {points: 20, answer: 'Boo'},
      {points: 17, answer: 'Creaking door'},
      {points: 10, answer: 'Spooky laugh'},
      {points: 8, answer: 'Moaning'},
      {points: 7, answer: 'Howling'},
    ],
  },
  {
    question: 'Name something people wear to scare off evil spirits.',
    answers: [
      {points: 65, answer: 'Garlic'},
      {points: 30, answer: 'Cross/Crucifix'},
      {points: 3, answer: 'Crystals'},
      {points: 2, answer: 'Mask'},
    ],
  },
  {
    question:
      'What time do most children start trick or treating on Halloween night?',
    answers: [
      {points: 54, answer: '6:00 p.m.'},
      {points: 21, answer: '5:00 p.m.'},
      {points: 12, answer: '7:00 p.m.'},
      {points: 8, answer: 'Dusk'},
      {points: 6, answer: '6:30 p.m.'},
    ],
  },
];
